# Generated by Django 3.2.12 on 2022-02-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogdetailpage_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='blog_image',
            new_name='banner_image',
        ),
    ]
