# Generated by Django 3.2.12 on 2022-02-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
