# Generated by Django 3.2.12 on 2022-02-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscirbers',
            new_name='Subscribers',
        ),
    ]
