# Generated by Django 3.2.12 on 2022-02-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_rename_subscirbers_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Subscribers', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
